### ISSUE TITLE
TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by jupe** [OpenTMI/opentmi#205]
### Description
- Type: Bug

---------------------------------------------------------------
## Bug

**opentmi version**
v0.5.5-39-ge29c5e8

**node.js version**
v6.9.1
5.1.281.84

**Expected Behavior**
no crash
**Actual Behavior**
```
warn: <Master> Master process exited with error code: 1.
/home/ubuntu/git/opentmi/node_modules/winston/lib/winston/logger.js:212
      throw ex;
      ^

TypeError: Cannot read property 'length' of undefined
    at Splatter._splat (/home/ubuntu/git/opentmi/node_modules/logform/splat.js:55:45)
    at Splatter.transform (/home/ubuntu/git/opentmi/node_modules/logform/splat.js:93:19)
    at Format.info [as transform] (/home/ubuntu/git/opentmi/node_modules/logform/combine.js:20:24)
    at DerivedLogger._transform (/home/ubuntu/git/opentmi/node_modules/winston/lib/winston/logger.js:210:29)
    at DerivedLogger.Transform._read (/home/ubuntu/git/opentmi/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at DerivedLogger.Transform._write (/home/ubuntu/git/opentmi/node_modules/readable-stream/lib/_stream_transform.js:172:83)
    at doWrite (/home/ubuntu/git/opentmi/node_modules/readable-stream/lib/_stream_writable.js:428:64)
    at writeOrBuffer (/home/ubuntu/git/opentmi/node_modules/readable-stream/lib/_stream_writable.js:417:5)
    at DerivedLogger.Writable.write (/home/ubuntu/git/opentmi/node_modules/readable-stream/lib/_stream_writable.js:334:11)
    at DerivedLogger.log (/home/ubuntu/git/opentmi/node_modules/winston/lib/winston/logger.js:143:12)
    at MasterLogger.log (/home/ubuntu/git/opentmi/app/tools/logger.js:93:17)
    at MasterLogger.silly (/home/ubuntu/git/opentmi/app/tools/logger.js:111:10)
    at Object.clusterEventHandler (/home/ubuntu/git/opentmi/app/tools/eventBus/index.js:16:12)
    at Worker.onWorkerMessage (/home/ubuntu/git/opentmi/app/master.js:285:18)
    at emitTwo (events.js:111:20)
    at Worker.emit (events.js:191:7)
```

**Comment by jupe** [comment]
Root cause seems to be this: https://github.com/winstonjs/logform/issues/40
